/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetocadastro;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhonnathan
 */
public class TelaCadastro extends javax.swing.JFrame {
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldMarca = new javax.swing.JTextField();
        fieldModelo = new javax.swing.JTextField();
        fieldAno = new javax.swing.JTextField();
        fieldMotor = new javax.swing.JTextField();
        cadastrarCarro = new javax.swing.JButton();
        fieldCor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarros = new javax.swing.JTable();
        editarCarro = new javax.swing.JButton();
        posicaoEditar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        removerCarro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastre seu carro");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fieldMarca.setToolTipText("");
        fieldMarca.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Marca"));
        fieldMarca.setCaretColor(new java.awt.Color(204, 0, 0));
        fieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMarcaActionPerformed(evt);
            }
        });

        fieldModelo.setToolTipText("");
        fieldModelo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Modelo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        fieldModelo.setCaretColor(new java.awt.Color(204, 0, 0));
        fieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldModeloActionPerformed(evt);
            }
        });

        fieldAno.setToolTipText("");
        fieldAno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ano"));
        fieldAno.setCaretColor(new java.awt.Color(204, 0, 0));
        fieldAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAnoActionPerformed(evt);
            }
        });

        fieldMotor.setToolTipText("");
        fieldMotor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Motor"));
        fieldMotor.setCaretColor(new java.awt.Color(204, 0, 0));
        fieldMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMotorActionPerformed(evt);
            }
        });

        cadastrarCarro.setBackground(new java.awt.Color(204, 0, 0));
        cadastrarCarro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarCarro.setText("Cadastrar");
        cadastrarCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cadastrarCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadastrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCarroActionPerformed(evt);
            }
        });

        fieldCor.setToolTipText("");
        fieldCor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cor"));
        fieldCor.setCaretColor(new java.awt.Color(204, 0, 0));
        fieldCor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCorActionPerformed(evt);
            }
        });

        tbCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Marca", "Modelo", "Ano", "Cor","Motor"
            }
        ));
        jScrollPane1.setViewportView(tbCarros);

        editarCarro.setBackground(new java.awt.Color(204, 0, 0));
        editarCarro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editarCarro.setText("Editar");
        editarCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        editarCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                meuBotaoMouseEntered(evt);
            }
        });
        editarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCarroActionPerformed(evt);
            }
        });

        posicaoEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        posicaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoEditarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Posição do carro:");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        removerCarro.setBackground(new java.awt.Color(204, 0, 0));
        removerCarro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removerCarro.setText("Remover");
        removerCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        removerCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldMarca)
                                .addComponent(fieldModelo)
                                .addComponent(fieldAno)
                                .addComponent(fieldCor)
                                .addComponent(fieldMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cadastrarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(posicaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(removerCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posicaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removerCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    ListaCarro objLista = new ListaCarro();
    
    
    
    private void fieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldModeloActionPerformed

    private void fieldAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAnoActionPerformed

    private void fieldMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMotorActionPerformed

    private void cadastrarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCarroActionPerformed
        Carro carro = new Carro();
        
        carro.setMarca(fieldMarca.getText());
        carro.setModelo(fieldModelo.getText());
        carro.setAno(fieldAno.getText());
        carro.setCor(fieldCor.getText());
        carro.setMotor(fieldMotor.getText());
        
        objLista.setListaCarros(carro);
        
        fieldMarca.setText("");
        fieldModelo.setText("");
        fieldAno.setText("");
        fieldCor.setText("");
        fieldMotor.setText("");
        preencherTabela();
    }//GEN-LAST:event_cadastrarCarroActionPerformed
    public void preencherTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tbCarros.getModel();
        
        ArrayList<Carro> lista = objLista.getListaCarros();
            modelo.addRow(new Object[]{
                lista.get(lista.size()-1).getMarca(),
                lista.get(lista.size()-1).getModelo(),
                lista.get(lista.size()-1).getAno(),
                lista.get(lista.size()-1).getCor(),
                lista.get(lista.size()-1).getMotor()
    });
    }
    private void fieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMarcaActionPerformed

    private void fieldCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCorActionPerformed

    private void editarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCarroActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbCarros.getModel();
        ArrayList<Carro> lista = objLista.getListaCarros();
        int posicao = Integer.parseInt(posicaoEditar.getText())-1;
        if(posicao <= lista.size()){
            lista.get(posicao).setMarca(fieldMarca.getText());
            lista.get(posicao).setModelo(fieldModelo.getText());
            lista.get(posicao).setAno(fieldAno.getText());
            lista.get(posicao).setCor(fieldCor.getText());
            lista.get(posicao).setMotor(fieldMotor.getText());
            
            fieldMarca.setText("");
            fieldModelo.setText("");
            fieldAno.setText("");
            fieldCor.setText("");
            fieldMotor.setText("");
            posicaoEditar.setText("");
            
            modelo.setValueAt(lista.get(posicao).getMarca(), posicao, 0);
            modelo.setValueAt(lista.get(posicao).getModelo(), posicao, 1);
            modelo.setValueAt(lista.get(posicao).getAno(), posicao, 2);
            modelo.setValueAt(lista.get(posicao).getCor(), posicao, 3);
            modelo.setValueAt(lista.get(posicao).getMotor(), posicao, 4);
        }
        else {
            JOptionPane.showMessageDialog(null, "Carro não encontrado");
        }

    }//GEN-LAST:event_editarCarroActionPerformed
 
    private void posicaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicaoEditarActionPerformed

    private void meuBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meuBotaoMouseEntered
        editarCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removerCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_meuBotaoMouseEntered

    private void removerCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCarroActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbCarros.getModel();
        ArrayList<Carro> lista = objLista.getListaCarros();
        int posicao = Integer.parseInt(posicaoEditar.getText())-1;
        if(!lista.isEmpty()&& posicao <= lista.size()-1){
            lista.remove(posicao);
            modelo.removeRow(posicao);
            posicaoEditar.setText("");
        }
        else { 
            JOptionPane.showMessageDialog(null, "Carro não encontrado");
            posicaoEditar.setText("");
        }
    }//GEN-LAST:event_removerCarroActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarCarro;
    private javax.swing.JButton editarCarro;
    private javax.swing.JTextField fieldAno;
    private javax.swing.JTextField fieldCor;
    private javax.swing.JTextField fieldMarca;
    private javax.swing.JTextField fieldModelo;
    private javax.swing.JTextField fieldMotor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField posicaoEditar;
    private javax.swing.JButton removerCarro;
    private javax.swing.JTable tbCarros;
    // End of variables declaration//GEN-END:variables
}
